### ISSUE TITLE
Unexpected FTP path (new server?) on database download

### ISSUE THREAD

**Issue by schorlton** [SJTU-CGM/CDKAM#3]
```
CDKAM-1.0$ ./download --download-library bacteria --db custom --threads 4
Downloading bacteria data:
rsync_from_ncbi.pl: unexpected FTP path (new server?) for na
```

Also tried it with the code on master and the `--use-ftp` flag - no go. Thanks!

**Comment by buikiendp** [comment]
This problem has been solved.
![Capture](https://user-images.githubusercontent.com/61977367/100547705-c23c0d80-329a-11eb-91c4-5bb273605859.PNG)

**Comment by Sanrrone** [comment]
Hi,
I have the same error using the lastet version and cloning the repo.
what should I do?

thanks in advance

**Comment by buikiendp** [comment]
> Hi, I have the same error using the latest version and cloning the repo. what should I do?
> 
> thanks in advance

Please change line 48 in rsync_from_ncbi.pl to this one to download the database from the NCBI. There has been a change in the NCBI recently.
`if (! ($full_path =~ s#^https://${qm_server}${qm_server_path}/##)) {`

**Comment by Sanrrone** [comment]
it works, but, the links seems looking for the incorrect file:
```
Step 1/4: Performing rsync file transfer of requested files
rsync: link_stat "/all/GCF/013/088/355/GCF_013088355.1_ASM1308835v1/GCF_013088355.1_ASM1308835v1_genomic.fna.gz" (in genomes) failed: No such file or directory (2)
rsync: link_stat "/all/GCF/001/714/535/GCF_001714535.1_ViralProj339884/GCF_001714535.1_ViralProj339884_genomic.fna.gz" (in genomes) failed: No such file or directory (2)
rsync: link_stat "/all/GCF/002/625/345/GCF_002625345.1_ASM262534v1/GCF_002625345.1_ASM262534v1_genomic.fna.gz" (in genomes) failed: No such file or directory (2)
rsync: link_stat "/all/GCF/002/270/705/GCF_002270705.1_ViralProj399968/GCF_002270705.1_ViralProj399968_genomic.fna.gz" (in genomes) failed: No such file or directory (2)
rsync: link_stat "/all/GCF/002/270/605/GCF_002270605.1_ViralProj399944/GCF_002270605.1_ViralProj399944_genomic.fna.gz" (in genomes) failed: No such file or directory (2)
rsync: link_stat "/all/GCF/001/579/475/GCF_001579475.1_ViralProj313446/GCF_001579475.1_ViralProj313446_genomic.fna.gz" (in genomes) failed: No such file or directory (2)
rsync: link_stat "/all/GCF/018/589/505/GCF_018589505.1_ASM1858950v1/GCF_018589505.1_ASM1858950v1_genomic.fna.gz" (in genomes) failed: No such file or directory (2)
rsync: link_stat "/all/GCF/002/613/105/GCF_002613105.1_ASM261310v1/GCF_002613105.1_ASM261310v1_genomic.fna.gz" (in genomes) failed: No such file or directory (2)
rsync: link_stat "/all/GCF/013/088/435/GCF_013088435.1_ASM1308843v1/GCF_013088435.1_ASM1308843v1_genomic.fna.gz" (in genomes) failed: No such file or directory (2)
rsync: link_stat "/all/GCF/001/866/225/GCF_001866225.1_ViralProj351802/GCF_001866225.1_ViralProj351802_genomic.fna.gz" (in genomes) failed: No such file or directory (2)
rsync: link_stat "/all/GCF/009/932/015/GCF_009932015.1_ASM993201v1/GCF_009932015.1_ASM993201v1_genomic.fna.gz" (in genomes) failed: No such file or directory (2)
```
this is just the begining, the list is gigant of course. Is that ok?

**Comment by buikiendp** [comment]
There might be sth wrong with your network. When downloading the reference genome, it will be like this:
![image](https://user-images.githubusercontent.com/61977367/228592847-d152fc84-1554-4351-adcf-27891ecfc4ab.png)


Which kind of target did you select (bacteria, archaea or viral)?

**Comment by buikiendp** [comment]
Then, you will get the data like this: 
![image](https://user-images.githubusercontent.com/61977367/228597697-3a0888a6-97e6-4d36-a381-7bba009dcd2d.png)

**Comment by Sanrrone** [comment]
Hi, you are right something goes wrong with the internet of the server, now it works. 
Thanks you!
